services:
  app:
    container_name: disagro_react
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5173:5173
    env_file:
      - .env
    stdin_open: true
    tty: true
