services:
  api:
    container_name: disagro_api
    image: disagro_api
    depends_on:
      - db
    ports:
      - 8080:3000
    env_file:
      - .env.backend

  db:
    container_name: disagro_db
    image: postgres:17
    restart: always
    volumes:
      - ./pg:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env.backend
